### PR TITLE
Move db image to registry.redhat.io

### PR DESCRIPTION
**Pull request by savitojs**
**_registry.access.redhat.com_** is an unauthenticated registry and is replaced by **_registry.redhat.io_**, [^1] [^2]

Pulling image with docker result in error

```
❯ docker pull registry.access.redhat.com/rhel8/postgresql-16:latest
Error response from daemon: unsupported: This repo requires terms acceptance and is only available on registry.redhat.io
```

**Steps to fix:**

1. [Login to registry.redhat.io](https://access.redhat.com/RegistryAuthentication#using-authentication-3)

```
docker login registry.redhat.io
```

2. Image was successfully pulled from `registry.redhat.io` and db container was successfully up and running after this change

**Resources:**
[^1]: https://access.redhat.com/solutions/5057811
[^2]: https://access.redhat.com/RegistryAuthentication

### CODE REVIEW

**Comment by kadel** [comment]
Hi @savitojs thank you for this PR. 
Can you please add information that the logging into registry.redhat.io using podman or docker is now required to use postgresql image?

**Comment by benwilcock** [comment]
What's the advantage to using the authenticated registry? does this also affect the RHDH image?

**Comment by kadel** [comment]
> What's the advantage to using the authenticated registry? does this also affect the RHDH image?

It doesn't, the official RHDH Helm Chart and Operator should already use authenticated registry.

I originally used an unauthenticated registry just because it is easier to use (no login step required). It looks like something changed and this PSQL image is no longer available via unauth. registry :-(

**Comment by savitojs** [comment]
@kadel I just added steps for registry login. Please let me know if I missed anything.
Thank you :tada:

**Comment by kadel** [comment]
@savitojs, this is perfect, thank you 👍

**Pull request merged**
